class MyPath {
  static List<String> get path => [
        'assets/images/baa.png',
        'assets/images/avstiraliya.png',
        'assets/images/canada.png',
        'assets/images/shivit.png',
        'assets/images/xitoy.jpeg',
        'assets/images/danya.jpeg',
        'assets/images/misr.png',
        'assets/images/eur.png',
        'assets/images/angiliya.png',
        'assets/images/insland.png',
        'assets/images/yapon.jpeg',
        'assets/images/koria.png',
        'assets/images/quvayt.png',
        'assets/images/qozoq.png',
        'assets/images/livan.png',
        'assets/images/malayziya.png',
        'assets/images/narvik.jpeg',
        'assets/images/polsha.jpeg',
        'assets/images/rus.jpeg',
        'assets/images/shivit.png',
        'assets/images/singapur.jpeg',
        'assets/images/turk.png',
        'assets/images/ukraina.png',
        'assets/images/aqsh.png',
      ];
}
